---
#### node-exporter vars
exporter_options:
  # - "--collector.arp" ## Enable the arp collector (default: enabled).
  # - "--collector.bcache" ## Enable the bcache collector (default: enabled).
  # - "--collector.bonding" ## Enable the bonding collector (default: enabled).
  # - "--collector.btrfs" ## Enable the btrfs collector (default: enabled).
  # - "--collector.buddyinfo" ## Enable the buddyinfo collector (default: disabled).
  # - "--collector.conntrack" ## Enable the conntrack collector (default: enabled).
  # - "--collector.cpu" ## Enable the cpu collector (default: enabled).
  # - "--collector.cpufreq" ## Enable the cpufreq collector (default: enabled).
  # - "--collector.diskstats" ## Enable the diskstats collector (default: enabled).
  # - "--collector.drbd" ## Enable the drbd collector (default: disabled).
  # - "--collector.edac" ## Enable the edac collector (default: enabled).
  # - "--collector.entropy" ## Enable the entropy collector (default: enabled).
  # - "--collector.fibrechannel" ## Enable the fibrechannel collector (default: enabled).
  # - "--collector.filefd" ## Enable the filefd collector (default: enabled).
  # - "--collector.filesystem" ## Enable the filesystem collector (default: enabled).
  # - "--collector.hwmon" ## Enable the hwmon collector (default: enabled).
  # - "--collector.infiniband" ## Enable the infiniband collector (default: enabled).
  # - "--collector.interrupts" ## Enable the interrupts collector (default: disabled).
  # - "--collector.ipvs" ## Enable the ipvs collector (default: enabled).
  # - "--collector.ksmd" ## Enable the ksmd collector (default: disabled).
  # - "--collector.loadavg" ## Enable the loadavg collector (default: enabled).
  # - "--collector.logind" ## Enable the logind collector (default: disabled).
  # - "--collector.mdadm" ## Enable the mdadm collector (default: enabled).
  # - "--collector.meminfo" ## Enable the meminfo collector (default: enabled).
  # - "--collector.meminfo_numa" ## Enable the meminfo_numa collector (default: disabled).
  # - "--collector.mountstats" ## Enable the mountstats collector (default: disabled).
  # - "--collector.netclass" ## Enable the netclass collector (default: enabled).
  # - "--collector.netdev" ## Enable the netdev collector (default: enabled).
  # - "--collector.netstat" ## Enable the netstat collector (default: enabled).
  # - "--collector.network_route" ## Enable the network_route collector (default: disabled).
  # - "--collector.nfs" ## Enable the nfs collector (default: enabled).
  # - "--collector.nfsd" ## Enable the nfsd collector (default: enabled).
  # - "--collector.ntp" ## Enable the ntp collector (default: disabled).
  # - "--collector.perf" ## Enable the perf collector (default: disabled).
  # - "--collector.powersupplyclass" ## Enable the powersupplyclass collector (default: enabled).
  # - "--collector.pressure" ## Enable the pressure collector (default: enabled).
  - "--collector.processes" ## Enable the processes collector (default: disabled).
  # - "--collector.qdisc" ## Enable the qdisc collector (default: disabled).
  # - "--collector.rapl" ## Enable the rapl collector (default: enabled).
  # - "--collector.runit" ## Enable the runit collector (default: disabled).
  # - "--collector.schedstat" ## Enable the schedstat collector (default: enabled).
  # - "--collector.sockstat" ## Enable the sockstat collector (default: enabled).
  # - "--collector.softnet" ## Enable the softnet collector (default: enabled).
  # - "--collector.stat" ## Enable the stat collector (default: enabled).
  # - "--collector.supervisord" ## Enable the supervisord collector (default: disabled).
  - "--collector.systemd" ## Enable the systemd collector (default: disabled).
  # - "--collector.tcpstat" ## Enable the tcpstat collector (default: disabled).
  # - "--collector.textfile" ## Enable the textfile collector (default: enabled).
  # - "--collector.thermal_zone" ## Enable the thermal_zone collector (default: enabled).
  # - "--collector.time" ## Enable the time collector (default: enabled).
  # - "--collector.timex" ## Enable the timex collector (default: enabled).
  # - "--collector.udp_queues" ## Enable the udp_queues collector (default: enabled).
  # - "--collector.uname" ## Enable the uname collector (default: enabled).
  # - "--collector.vmstat" ## Enable the vmstat collector (default: enabled).
  # - "--collector.wifi" ## Enable the wifi collector (default: disabled).
  # - "--collector.xfs" ## Enable the xfs collector (default: enabled).
  # - "--collector.zfs" ## Enable the zfs collector (default: enabled).
  # - "--collector.zoneinfo" ## Enable the zoneinfo collector (default: disabled).
