---
- name: Install monitoring agents
  hosts: monitoring
  gather_facts: true
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - include_role: 
        name: node_exporter
      tags: node_exporter

    - include_role: 
        name: cadvisor_exporter
      tags: cadvisor_exporter 




