---
- name: Install monitoring server
  hosts: monitoring-server
  gather_facts: true
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - include_role: 
        name: prometheus
      tags: prometheus





