---
- name: Install logging server
  hosts: logging-server
  gather_facts: true
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - include_role: 
        name: loki
      tags: loki





