---
- name: Install graphics agents
  hosts: graphics-server
  gather_facts: true
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - include_role: 
        name: grafana
      tags: grafana





