---
- name: Install logging agents
  hosts: graphics-server
  gather_facts: true
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - include_role: 
        name: promtail_agent
      tags: promtail_agent





