---
- name: "Deploy cadvisor_exporter"
  community.docker.docker_container:
    name: "cadvisor-exporter"
    recreate: true
    image: gcr.io/cadvisor/cadvisor:latest
    network_mode: host
    pid_mode: host
    restart_policy: unless-stopped
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    devices:
      - "/dev/kmsg:/dev/kmsg"
    privileged: true
  become: true
  when: action == "deploy"


- name: "Remove cadvisor_exporter"
  community.docker.docker_container:
    name: "cadvisor-exporter"
    state: absent
  become: true
  when: action == "remove"
